# --- FINAL PRODUCTION netlify.toml ---
[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
