# The final, correct, and complete netlify.toml file

[build]
  publish = "public"
  functions = "netlify/functions"
  command = "# No build command needed"

# This plugin ensures your function dependencies from package.json are installed.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# --- API Redirects ---
[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
