[build]
  publish = "public"
  functions = "netlify/functions" # This should bundle all functions, including nested ones
  command = "# No build command needed"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# All [[redirects]] rules are REMOVED.
