[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Removed: Redirect for the Lag Report Validation tool (as it's now client-side only)
# [[redirects]]
#   from = "/api/lag-report-validation"
#   to = "/.netlify/functions/lag-report-validation"
#   status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"
