[build]
  publish = "public"
  command = "# No build command needed"

# --- Netlify Functions Configuration ---
[functions]
  directory = "netlify/functions"

# --- Netlify Plugins Configuration ---
# This needs to be an array of tables, hence the double brackets [[plugins]]
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# --- NO [[redirects]] RULES ---
# Frontend calls should now directly hit paths like /.netlify/functions/user-auth-register
