[build]
  publish = "public"
  command = "# No build command needed"

# --- Netlify Functions Configuration ---
# This single line tells Netlify to look for functions in 'netlify/functions'
# and its subdirectories. Since your other function folders (admin, data-dictionary,
# file-management, user-auth) each have a package.json, Netlify will discover
# and bundle them correctly.
[functions]
  directory = "netlify/functions"

# --- Netlify Plugins Configuration ---
# This needs to be an array of tables, hence the double brackets [[plugins]]
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# --- NO [[redirects]] RULES ---
# Frontend calls should now directly hit paths like /.netlify/functions/user-auth-register
