# The correct and complete netlify.toml file

[build]
  publish = "public"
  functions = "netlify/functions"

# This rule handles the admin data function
[[redirects]]
  from = "/api/admin/get-company-admin-data"
  to = "/.netlify/functions/admin/get-company-admin-data"
  status = 200

# This rule handles the other admin functions
[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin/:splat"
  status = 200

# This rule handles all other non-admin functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
