# The final, correct, and complete netlify.toml file

[build]
  publish = "public"
  command = "# No build command needed" # Keep this, as functions are handled by functions settings/plugins

# --- Netlify Functions Configuration ---
# Define each function directory as a separate functions source to ensure they are all built.
# This explicitly tells Netlify to look into these subdirectories for functions.

[[functions]]
  directory = "netlify/functions/user-auth"
  # Optional: You can specify node_bundler = "esbuild" or "zip" if needed,
  # but Netlify usually defaults to esbuild for JS/TS functions.

[[functions]]
  directory = "netlify/functions/admin"

[[functions]]
  directory = "netlify/functions/file-management"

[[functions]]
  directory = "netlify/functions/data-dictionary"

# For the top-level clean-excel.js (if it's not in a subdirectory)
# If clean-excel.js is directly under netlify/functions, it should be fine with the default functions = "netlify/functions"
# but since the log only picked it up, it might be the *only* one directly there.
# If it's truly standalone, you might define it like this:
[[functions]]
  directory = "netlify/functions" # This captures clean-excel.js and any other root-level functions

# This plugin ensures your function dependencies from the root package.json are installed.
# It helps with shared node_modules for all functions.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# --- API Redirects ---
# These rules map frontend API calls (e.g., /api/register) to Netlify's deployed function paths.
# Netlify by default flattens functions in subdirectories by replacing '/' with '-' (e.g., user-auth/register.js becomes user-auth-register).

# User Authentication Functions
[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/user-auth-register"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/user-auth-login"
  status = 200

# Admin Functions
[[redirects]]
  from = "/api/admin/get-company-admin-data"
  to = "/.netlify/functions/admin-get-company-admin-data"
  status = 200

[[redirects]]
  from = "/api/admin/get-company-users"
  to = "/.netlify/functions/admin-get-company-users"
  status = 200

[[redirects]]
  from = "/api/admin/update-company-defaults"
  to = "/.netlify/functions/admin-update-company-defaults"
  status = 200

[[redirects]]
  from = "/api/admin/update-user-tools"
  to = "/.netlify/functions/admin-update-user-tools"
  status = 200

[[redirects]]
  from = "/api/admin/get-all-companies"
  to = "/.netlify/functions/admin-get-all-companies"
  status = 200

[[redirects]]
  from = "/api/admin/get-all-tools"
  to = "/.netlify/functions/admin-get-all-tools"
  status = 200

# File Management Functions
[[redirects]]
  from = "/api/delete-file"
  to = "/.netlify/functions/file-management-delete-file"
  status = 200

[[redirects]]
  from = "/api/get-file"
  to = "/.netlify/functions/file-management-get-file"
  status = 200

[[redirects]]
  from = "/api/list-files"
  to = "/.netlify/functions/file-management-list-files"
  status = 200

[[redirects]]
  from = "/api/upload-file"
  to = "/.netlify/functions/file-management-upload-file"
  status = 200

# Data Dictionary Functions
[[redirects]]
  from = "/api/delete-data-dictionary"
  to = "/.netlify/functions/data-dictionary-delete-data-dictionary"
  status = 200

[[redirects]]
  from = "/api/get-data-dictionary"
  to = "/.netlify/functions/data-dictionary-get-data-dictionary"
  status = 200

[[redirects]]
  from = "/api/list-data-dictionaries"
  to = "/.netlify/functions/data-dictionary-list-data-dictionaries"
  status = 200

[[redirects]]
  from = "/api/save-data-dictionary"
  to = "/.netlify/functions/data-dictionary-save-data-dictionary"
  status = 200

# Other Functions
[[redirects]]
  from = "/api/clean-excel"
  to = "/.netlify/functions/clean-excel" # This one is directly in netlify/functions
  status = 200
