[build]
  publish = "public"
  # This command ensures dependencies are installed for both the root project
  # and all your nested Netlify Functions.
  command = "npm install && cd netlify/functions/admin && npm install && cd ../data-dictionary && npm install && cd ../file-management && npm install && cd ../user-auth && npm install && cd ../../"

# --- Netlify Functions Configuration ---
# This specifies the base directory where Netlify will look for your serverless functions.
# Netlify will automatically discover functions within this directory and its subdirectories
# if they contain valid Node.js function files and their own package.json for dependencies.
[functions]
  directory = "netlify/functions"

# --- Netlify Plugins Configuration ---
# This section defines any Netlify Build plugins you want to use.
# It must be an array of tables, hence the double brackets `[[plugins]]`.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
  # You can add inputs for the plugin here if needed, e.g.,
  # inputs = { some_input = "value" }

# --- Redirects (Optional) ---
# This section is commented out as per your previous note.
# If you need any redirect rules in the future, you would define them here.
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# --- Headers (Optional) ---
# This section is for custom HTTP response headers.
# [[headers]]
#   for = "/*"
#   values = {
#     "X-Frame-Options" = "DENY",
#     "Strict-Transport-Security" = "max-age=63072000; includeSubDomains; preload"
#   }
