# The final, correct netlify.toml file with a flat function structure

[build]
  publish = "public"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# --- API Redirects ---
# Point the old admin paths to the new top-level function files
[[redirects]]
  from = "/api/admin/get-company-admin-data"
  to = "/.netlify/functions/get-company-admin-data"
  status = 200

[[redirects]]
  from = "/api/admin/update-company-defaults"
  to = "/.netlify/functions/update-company-defaults"
  status = 200

[[redirects]]
  from = "/api/admin/update-user-tools"
  to = "/.netlify/functions/update-user-tools"
  status = 200

# This rule handles all other non-admin functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
