[build]
  publish = "public"
  # IMPORTANT: This command will now ensure dependencies are installed for all your functions
  command = "npm install && cd netlify/functions/user-auth && npm install && cd ../admin && npm install && cd ../data-dictionary && npm install && cd ../file-management && npm install && cd ../../" # Add more `cd` and `npm install` commands for any other function directories you have.

# --- Netlify Functions Configuration ---
[functions]
  directory = "netlify/functions"

# --- Netlify Plugins Configuration ---
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# --- NO [[redirects]] RULES ---
# Frontend calls should now directly hit paths like /.netlify/functions/user-auth-register
