[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure this redirect rule is present and correctly spelled:
[[redirects]]
  from = "/api/lag-report-validation"
  to = "/.netlify/functions/lag-report-validation"
  status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"
