# The correct and complete netlify.toml file for RCMBuddy

[build]
  publish = "public"
  functions = "netlify/functions"

# This plugin is required for your function dependencies.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# --- API Redirects ---
# This rule handles all admin functions, including the one that is failing.
[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin/:splat"
  status = 200

# This rule handles all other non-admin functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
